### ISSUE TITLE
Mettre à jour le tuto

### ISSUE THREAD

**Issue by Corbichon** [Corbichon/jaboog#60]
Img 2 : mélangé  parties = > mélangé 1 partie
Img 4 : le compte premium permet d'avoir accès aux séries des 10 semaines précédentes

**Comment by Corbichon** [comment]
@Gabrielchebrou 
C'est dommage de ne laisser que les dix dernières semaines alors qu'on a toutes les archives de disponibles nan?

**Comment by Corbichon** [comment]
![screenshot_1484233644](https://cloud.githubusercontent.com/assets/22273041/21894934/4304dc0c-d8e1-11e6-9803-5fa35f96ce0f.png)

@Gabrielchebrou Et je trouve ca un peu "aggressif" de faire de la pub pour le compte premium direct dans le tuto d’accueil alors qu'on le précise lorsque tu clique sur une série grisée dans la page de téléchargements de séries

**Comment by Gabrielchebrou** [comment]
SURTOUT PAS !!
Ca me permet de pouvoir ré-utiliser quelques questions d'une année sur l'autre, d’événements distants dans le temps (ex : JO, ...) et **surtout** ça évite de donner des contradictions (style un politique à dit ça, puis il s'est ravisé mais la question est toujours là).
C'est hyper important que non ! C'est la magie de Jaboog !
On peut pousser a 15 si tu veux faire du contenu mais c'est vraiment le grand grand max, ça fait 3 mois c'est beaucoup et ça a pas vraiment de sens avec notre politique de quiz d'actualité.

**Comment by Gabrielchebrou** [comment]
J'avais pas vu que c'était actuellement toutes les séries proposées, mais on avait parlé de 10 seulement, c'est pourquoi je t'ai filé que les dix dernières quand on a mis le système en place.

**Comment by Corbichon** [comment]
Ca roule, je descend à 10 et je modifie le tuto

**Comment by Corbichon** [comment]
@Gabrielchebrou  
Et on vend quand même le compte premium dans le tuto ou pas?

**Comment by Gabrielchebrou** [comment]
Je pense que c'est utile de le mentionner vite fait dans le tuto afin que les gens sachent qu'il existe.
Du style : 
"Le compte Premium permet d’accéder aux séries des dix semaines précédentes"
ou "des deux derniers mois"

**Comment by Corbichon** [comment]
![screenshot_1484237918](https://cloud.githubusercontent.com/assets/22273041/21897887/32dfabd6-d8eb-11e6-8aec-e35f70001938.png)
